create sequence product_id_seq start 29 increment 1;
create sequence users_id_seq start 4 increment 1;
create sequence order_item_seq start 1 increment 1;
create sequence orders_seq start 1 increment 1;

create table orders
(
    id           int8 generated by default as identity,
    address      varchar(255) not null,
    city         varchar(255) not null,
    date         timestamp default current_timestamp,
    email        varchar(255) not null,
    first_name   varchar(255) not null,
    last_name    varchar(255) not null,
    phone_number varchar(255) not null,
    post_index   int4 not null,
    total_price  float8 not null,
    user_id      int8,
    primary key (id)
);

create table orders_products
(
    order_id    int8 not null,
    products_id  int8 not null
);

create table products
(
    id          int8 not null,
    category    varchar(255) not null,
    description text,
    filename    varchar(255),
    price       int4 not null,
    product_name varchar(255) not null,
    specifications text,
    stock       int4 not null,
    release_year int4 not null,
    primary key (id)
);

create table user_role
(
    user_id int8 not null,
    roles   varchar(255)
);

create table users
(
    id                  int8    not null,
    activation_code     varchar(255),
    active              boolean not null,
    address             varchar(255),
    city                varchar(255),
    email               varchar(255) not null,
    first_name          varchar(255) not null,
    last_name           varchar(255),
    password            varchar(255) not null,
    password_reset_code varchar(255),
    phone_number        varchar(255),
    post_index          varchar(255),
    primary key (id)
);

create table users_product_list
(
    user_id         int8 not null,
    product_list_id int8 not null
);

-- 外键约束
alter table if exists orders
    add constraint FK_orders_user_id foreign key (user_id) references users;

alter table if exists orders_products
    add constraint FK_orders_products_order_id foreign key (order_id) references orders;
alter table if exists orders_products
    add constraint FK_orders_products_product_id foreign key (products_id) references products;

alter table if exists user_role
    add constraint FK_user_role_user_id foreign key (user_id) references users;

alter table if exists users_product_list
    add constraint FK_users_product_list_user_id foreign key (user_id) references users;
alter table if exists users_product_list
    add constraint FK_users_product_list_product_id foreign key (product_list_id) references products;